### PR TITLE
ADDED: humaneval-x rust integration

### PR DESCRIPTION
**Pull request by roG0d**
# Humaneval-x integration with rust
With this pull request, we introduce the possiblity of evaluating code generations written in rust. 
The main features are:

 - **Humaneval-rust:** Full translation of the 164 problems consisting of the initial benchmark into rust language
 - **Evaluation environment for rust in Humaneval-x:** Integration of humaneval-x for rust, achieving the evaluation based on the compilation and execution of the generated code following the humaneval-x metrics and procedures.
# Additions

-   evaluate_humaneval_x.py script created based on homonymous .sh script
    
-   Added a path for the rust language on methods **process_humaneval_test** and **check_correctness**
    
-   Path for the dataset: CODEGEEX/codegeex/humaneval-x/rust
-  Path for the generations: CODEGEEX/generations
    
-   Added compilation and execution environment path: CODEGEEX/codegeex/benchmark/rust
    

# Modifications

-   **evaluate_humnaeval_x.py** copied into  CODEGEEX/codegeex/benchmark in order to debug and execute script **evaluate_humaneval_x.py** from CODEGEEX/scripts

# Testing 
For testing uses, we have included a dummy generation of rust code located in CODEGEEX/generations/humaneval_rust_generations_results.jsonl.gz. This generations consists of a copy of every canonical solutions for every problem imitating possibles generations, in order to achieve a pass@k of 1.0
In order to run it. Once codegeex is installed following the project README.md. 
You can run the following command:

    bash ./scripts/evaluate_humaneval_x.sh ./generations/humaneval_rust_generations.jsonl.gz rust 64 300 

or run the`./scripts/evaluate_humaneval_x.py` script (especially for debugging)

# Noteworthy details
- For every compilation/execution. It can be found a rust_task_id.jsonl (codegeex/benchmark/rust/tmp/logs) giving further information about its process.
- Due to the compilation time needed for cargo in every thread, the standard timeout is >300 to ensure every task is compilated and executed.
- The **Rust/32** test has **unexpected behavior** due to the nature of the test code (not just for rust). For the moment, the test code is commented to not interrupt the process of evaluating the rust code. But further work is needed to fix it.

Work done by @antferdom and @roG0d.

### CODE REVIEW

**Comment by Stanislas0** [comment]
Great work on the Rust integration of HumanEval-X! Thanks!

**Comment by Stanislas0** [comment]
Great work on the Rust integration of HumanEval-X! Thanks!

**Comment by Muennighoff** [comment]
@roG0d Can you elaborate on `The Rust/32 test has unexpected behavior due to the nature of the test code (not just for rust). For the moment, the test code is commented to not interrupt the process of evaluating the rust code. But further work is needed to fix it.`? For me the test is passing when I uncomment it as expected.

**Comment by Muennighoff** [comment]
Thanks! Also unlike the other languages, in Rust the `prompt` field does not contain the `declaration` field, correct? I.e. at evaluation, we should concat `\nfn main(){ \n } \n`, prompt & declaration as input to the model, right?

**Comment by roG0d** [comment]
Yes, apart from that subtle change, the Rust dataset has the same parts as the others. It was made this way to individually have the function header from the docstring. [Part of evaluate_humaneval_x.py](https://github.com/THUDM/CodeGeeX/pull/76/commits/f66205b5f615a4eead9c26d7ec297e14738ea18d#diff-d900db0a99855597abf59e8c1f894e97f661625c00e8a9defd0dc88f2ef0ad16)

**Comment by Muennighoff** [comment]
> Yes @Muennighoff, apart from that subtle change, the Rust dataset has the same parts as the others. It was made this way to individually have the function header from the docstring. So we could give it to the model for generations.
> 
> For evaluation inside Humaneval-X the program is already created as you can see here in this [part of evaluate_humaneval_x.py](https://github.com/THUDM/CodeGeeX/pull/76/commits/f66205b5f615a4eead9c26d7ec297e14738ea18d#diff-d900db0a99855597abf59e8c1f894e97f661625c00e8a9defd0dc88f2ef0ad16) where what you said its already done!

Sorry for digging this back up - I think I had misunderstood. 
At generation time you do:
`prompt + declaration`
At evaluation time you do:
`\nfn main(){ \n } \n + declaration + generated_code + tests`
correct?

**Pull request merged**
